// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MlNetAppML.Model
{
    public class ModelInput
    {
        [ColumnName("Comment"), LoadColumn(0)]
        public string Comment { get; set; }


        [ColumnName("Sentiment"), LoadColumn(1)]
        public string Sentiment { get; set; }


    }
}
